version: "3.6"

services:
  nginx:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    hostname: api_nginx
    container_name: api_nginx
    restart: unless-stopped
    environment:
      - HTTP_PORT=80
      - APP_NAME=api_app
    volumes:
      - .:/app
    ports:
      - "80:80"
  postgresql:
    build:
      context: .
      dockerfile: ./Docker/postgresql/Dockerfile
    hostname: api_postgresql
    container_name: api_postgresql
    restart: unless-stopped
    volumes:
      - ./var/postgresql:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    hostname: api_app
    container_name: api_app
    restart: unless-stopped
    volumes:
      - .:/app
